FROM node:22.18.0-slim

RUN apt-get update && apt-get install curl make -y \
    && apt-get install libsqlite3-dev bzip2 icu-devtools uuid-dev -y

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SSO_URL
ARG NEXT_PUBLIC_SSO_CLIENT_ID
ARG NEXT_PUBLIC_SSO_REDIRECT_URI
ARG NEXT_PUBLIC_SSO_AUTHORIZATION_RESPONSE_TYPE
ARG NEXT_PUBLIC_SSO_AUTHORIZATION_SCOPE
ARG NEXT_PUBLIC_SSO_TOKEN_GRANT_TYPE
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_INCLUDE_DIGITAL_CREDENTIAL
ARG NEXT_PUBLIC_INCLUDE_BC_SERVICES_CARD
ARG NEXT_PUBLIC_ALLOW_BC_SERVICES_CARD_PROD
ARG NEXT_PUBLIC_INCLUDE_SOCIAL
ARG NEXT_PUBLIC_INCLUDE_OTP
ARG NEXT_PUBLIC_SSO_CONFIGURATION_ENDPOINT
ARG NEXT_PUBLIC_APP_ENV

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
    NEXT_PUBLIC_SSO_URL=${NEXT_PUBLIC_SSO_URL} \
    NEXT_PUBLIC_SSO_CLIENT_ID=${NEXT_PUBLIC_SSO_CLIENT_ID} \
    NEXT_PUBLIC_SSO_REDIRECT_URI=${NEXT_PUBLIC_SSO_REDIRECT_URI} \
    NEXT_PUBLIC_SSO_AUTHORIZATION_RESPONSE_TYPE=${NEXT_PUBLIC_SSO_AUTHORIZATION_RESPONSE_TYPE} \
    NEXT_PUBLIC_SSO_AUTHORIZATION_SCOPE=${NEXT_PUBLIC_SSO_AUTHORIZATION_SCOPE} \
    NEXT_PUBLIC_SSO_TOKEN_GRANT_TYPE=${NEXT_PUBLIC_SSO_TOKEN_GRANT_TYPE} \
    NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL} \
    NEXT_PUBLIC_INCLUDE_DIGITAL_CREDENTIAL=${NEXT_PUBLIC_INCLUDE_DIGITAL_CREDENTIAL} \
    NEXT_PUBLIC_INCLUDE_BC_SERVICES_CARD=${NEXT_PUBLIC_INCLUDE_BC_SERVICES_CARD} \
    NEXT_PUBLIC_ALLOW_BC_SERVICES_CARD_PROD=${NEXT_PUBLIC_ALLOW_BC_SERVICES_CARD_PROD} \
    NEXT_PUBLIC_INCLUDE_SOCIAL=${NEXT_PUBLIC_INCLUDE_SOCIAL} \
    NEXT_PUBLIC_INCLUDE_OTP=${NEXT_PUBLIC_INCLUDE_OTP} \
    NEXT_PUBLIC_SSO_CONFIGURATION_ENDPOINT=${NEXT_PUBLIC_SSO_CONFIGURATION_ENDPOINT} \
    NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}

WORKDIR /app

# Set the environment to production
ENV NODE_ENV=production

COPY *.json ./

COPY app ./app

COPY db ./db

COPY Makefile ./

RUN make app_install

RUN make disable_telemetry

RUN make db_install

RUN make db_compile

RUN make app_build

ENTRYPOINT ["/bin/sh", "-c" , "make migrations && make app_start"]
