{{- if .Values.cronJobs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-cron" (include "..fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-cron" (include "..fullname" .) }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-cron" (include "..fullname" .) }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.cronJobs.image.repository }}:{{ .Values.cronJobs.image.tag }}"
          imagePullPolicy: {{ .Values.cronJobs.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: API_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: api-auth-secret
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: app-url
{{- end }}
