apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: app-url
            - name: API_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: api-auth-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-patroni-appusers" (include "..fullname" .) }}
                  key: username-appuser1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-patroni-appusers" (include "..fullname" .) }}
                  key: password-appuser1
            - name: DB_HOSTNAME
              value: sso-requests-patroni
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ssorequests
            - name: KEYCLOAK_V2_DEV_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-dev-url
            - name: KEYCLOAK_V2_DEV_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-dev-username
            - name: KEYCLOAK_V2_DEV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-dev-password
            - name: KEYCLOAK_V2_PROD_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-prod-url
            - name: KEYCLOAK_V2_PROD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-prod-username
            - name: KEYCLOAK_V2_PROD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-prod-password
            - name: KEYCLOAK_V2_TEST_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-test-url
            - name: KEYCLOAK_V2_TEST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-test-username
            - name: KEYCLOAK_V2_TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: keycloak-v2-test-password
            - name: CHES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: ches-username
            - name: CHES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: ches-password
            - name: GRAFANA_API_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: grafana-api-url
            - name: GRAFANA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: grafana-api-token
            - name: MS_GRAPH_API_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: ms-graph-api-authority
            - name: MS_GRAPH_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: ms-graph-api-client-id
            - name: MS_GRAPH_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: ms-graph-api-client-secret
            - name: BCSC_INITIAL_ACCESS_TOKEN_DEV
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: bcsc-initial-access-token-dev
            - name: BCSC_INITIAL_ACCESS_TOKEN_PROD
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: bcsc-initial-access-token-prod
            - name: BCSC_INITIAL_ACCESS_TOKEN_TEST
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: bcsc-initial-access-token-test
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: redis-host
            - name: GH_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: gh-access-token
            - name: VERIFY_USER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: verify-user-secret
            - name: RC_SSO_OPS_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: {{ include "..fullname" . }}
                  key: rc_webhook_url
            {{- range $key, $val := .Values.env }}
            - name: {{  $key | quote | upper }}
              value: {{ $val | quote }}
            {{- end }}
