{{- if .Values.requestMonitorJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-monitor" (include "..fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
spec:
  # daily at 2 am pst and 9 am utc
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "..name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.requestMonitorJob.image.repository }}:{{ .Values.requestMonitorJob.image.tag }}"
              imagePullPolicy: {{ .Values.requestMonitorJob.image.pullPolicy }}
              env:
                - name: RELEASE_REVISION
                  value: "{{ .Release.Revision }}"
                - name: DB_HOSTNAME
                  value: {{ printf "%s-patroni" (include "..fullname" .) }}
                - name: DB_PORT
                  value: "5432"
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ printf "%s-patroni-appusers" (include "..fullname" .) }}
                      key: username-appuser1
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ printf "%s-patroni-appusers" (include "..fullname" .) }}
                      key: password-appuser1
                - name: PGDATABASE
                  value: ssorequests
                - name: DEV_KEYCLOAK_URL
                  valueFrom:
                  secretKeyRef:
                    name: {{ include "..fullname" . }}
                    key: keycloak-v2-dev-url
                - name: DEV_KEYCLOAK_USERNAME
                  valueFrom:
                  secretKeyRef:
                    name: {{ include "..fullname" . }}
                    key: keycloak-v2-dev-username
                - name: DEV_KEYCLOAK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: keycloak-v2-dev-password
                - name: TEST_KEYCLOAK_URL
                  valueFrom:
                  secretKeyRef:
                    name: {{ include "..fullname" . }}
                    key: keycloak-v2-test-url
                - name: TEST_KEYCLOAK_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: keycloak-v2-test-username
                - name: TEST_KEYCLOAK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: keycloak-v2-test-password
                - name: PROD_KEYCLOAK_URL
                  valueFrom:
                  secretKeyRef:
                    name: {{ include "..fullname" . }}
                    key: keycloak-v2-prod-url
                - name: PROD_KEYCLOAK_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: keycloak-v2-prod-username
                - name: PROD_KEYCLOAK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: keycloak-v2-prod-password
                - name: RC_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: rc_webhook_url
                - name: DC_USERS_RETENTION_DAYS
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "..fullname" . }}
                      key: dc-users-retention-days
          restartPolicy: Never
{{- end }}
