apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
type: Opaque
data:
  api-auth-secret: {{ .Values.envVars.apiAuthSecret }}
  keycloak-v2-dev-username: {{ .Values.envVars.keycloakV2DevUsername }}
  keycloak-v2-dev-password: {{ .Values.envVars.keycloakV2DevPassword }}
  keycloak-v2-prod-username: {{ .Values.envVars.keycloakV2ProdUsername }}
  keycloak-v2-prod-password: {{ .Values.envVars.keycloakV2ProdPassword }}
  keycloak-v2-test-username: {{ .Values.envVars.keycloakV2TestUsername }}
  keycloak-v2-test-password: {{ .Values.envVars.keycloakV2TestPassword }}
  ches-username: {{ .Values.envVars.chesUsername }}
  ches-password: {{ .Values.envVars.chesPassword }}
  grafana-api-token: {{ .Values.envVars.grafanaApiToken }}
  ms-graph-api-authority: {{ .Values.envVars.msGraphApiAuthority }}
  ms-graph-api-client-id: {{ .Values.envVars.msGraphApiClientId }}
  ms-graph-api-client-secret: {{ .Values.envVars.msGraphApiClientSecret }}
  bcsc-initial-access-token-dev: {{ .Values.envVars.bcscInitialAccessTokenDev }}
  bcsc-initial-access-token-prod: {{ .Values.envVars.bcscInitialAccessTokenProd }}
  bcsc-initial-access-token-test: {{ .Values.envVars.bcscInitialAccessTokenTest }}
  redis-host: {{ .Values.envVars.redisHost }}
  gh-access-token: {{ .Values.envVars.ghAccessToken }}
