{{- $secretName := print (include "..fullname" .) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "..chart" . }}
type: Opaque
data:
  {{- if $secret }}
  app-url: {{  index $secret.data "app-url" }}
  api-auth-secret: {{  index $secret.data "api-auth-secret" }}
  keycloak-v2-dev-username: {{  index $secret.data "keycloak-v2-dev-username" }}
  keycloak-v2-dev-password: {{  index $secret.data "keycloak-v2-dev-password" }}
  keycloak-v2-prod-username: {{  index $secret.data "keycloak-v2-prod-username" }}
  keycloak-v2-prod-password: {{  index $secret.data "keycloak-v2-prod-password" }}
  keycloak-v2-test-username: {{  index $secret.data "keycloak-v2-test-username" }}
  keycloak-v2-test-password: {{  index $secret.data "keycloak-v2-test-password" }}
  keycloak-v2-dev-url: {{  index $secret.data "keycloak-v2-dev-url" }}
  keycloak-v2-test-url: {{  index $secret.data "keycloak-v2-test-url" }}
  keycloak-v2-prod-url: {{  index $secret.data "keycloak-v2-prod-url" }}
  ches-username: {{  index $secret.data "ches-username" }}
  ches-password: {{  index $secret.data "ches-password" }}
  grafana-api-url: {{  index $secret.data "grafana-api-url" }}
  grafana-api-token: {{  index $secret.data "grafana-api-token" }}
  ms-graph-api-authority: {{  index $secret.data "ms-graph-api-authority" }}
  ms-graph-api-client-id: {{  index $secret.data "ms-graph-api-client-id" }}
  ms-graph-api-client-secret: {{  index $secret.data "ms-graph-api-client-secret" }}
  bcsc-initial-access-token-dev: {{  index $secret.data "bcsc-initial-access-token-dev" }}
  bcsc-initial-access-token-prod: {{  index $secret.data "bcsc-initial-access-token-prod" }}
  bcsc-initial-access-token-test: {{  index $secret.data "bcsc-initial-access-token-test" }}
  redis-host: {{  index $secret.data "redis-host" }}
  gh-access-token: {{  index $secret.data "gh-access-token" }}
  verify-user-secret: {{  index $secret.data "verify-user-secret" }}
  rc_webhook_url: {{  index $secret.data "rc_webhook_url" }}
  {{- else }}
  app-url: {{ .Values.envVars.appUrl | b64enc }}
  api-auth-secret: {{ .Values.envVars.apiAuthSecret | b64enc }}
  keycloak-v2-dev-username: {{ .Values.envVars.keycloakV2DevUsername | b64enc }}
  keycloak-v2-dev-password: {{ .Values.envVars.keycloakV2DevPassword | b64enc }}
  keycloak-v2-prod-username: {{ .Values.envVars.keycloakV2ProdUsername | b64enc }}
  keycloak-v2-prod-password: {{ .Values.envVars.keycloakV2ProdPassword | b64enc }}
  keycloak-v2-test-username: {{ .Values.envVars.keycloakV2TestUsername | b64enc }}
  keycloak-v2-test-password: {{ .Values.envVars.keycloakV2TestPassword | b64enc }}
  keycloak-v2-dev-url: {{ .Values.envVars.keycloakV2DevUrl | b64enc }}
  keycloak-v2-test-url: {{ .Values.envVars.keycloakV2TestUrl | b64enc }}
  keycloak-v2-prod-url: {{ .Values.envVars.keycloakV2ProdUrl | b64enc }}
  ches-username: {{ .Values.envVars.chesUsername | b64enc }}
  ches-password: {{ .Values.envVars.chesPassword | b64enc }}
  grafana-api-url: {{ .Values.envVars.grafanaApiUrl | b64enc }}
  grafana-api-token: {{ .Values.envVars.grafanaApiToken | b64enc }}
  ms-graph-api-authority: {{ .Values.envVars.msGraphApiAuthority | b64enc }}
  ms-graph-api-client-id: {{ .Values.envVars.msGraphApiClientId | b64enc }}
  ms-graph-api-client-secret: {{ .Values.envVars.msGraphApiClientSecret | b64enc }}
  bcsc-initial-access-token-dev: {{ .Values.envVars.bcscInitialAccessTokenDev | b64enc }}
  bcsc-initial-access-token-prod: {{ .Values.envVars.bcscInitialAccessTokenProd | b64enc }}
  bcsc-initial-access-token-test: {{ .Values.envVars.bcscInitialAccessTokenTest | b64enc }}
  redis-host: {{ .Values.envVars.redisHost | b64enc }}
  gh-access-token: {{ .Values.envVars.ghAccessToken | b64enc }}
  verify-user-secret: {{ .Values.envVars.verifyUserSecret | b64enc }}
  rc_webhook_url: {{ .Values.envVars.rc_webhook_url | b64enc }}
  {{- end }}
{{- end }}
