openapi: 3.0.0
info:
  title: RDSI API
  description: RDSI API
  version: 1.0.0
  # TODO: (Nick) need to update descriptions and summaries

servers:
  - url: https://rdsi-server.adccd1-prod.apps.silver.devops.gov.bc.ca/api/v1
    description: RDSI API Production
  - url: http://localhost:8080/api/v1
    description: RDSI API Test
