const APP_URL = process.env.APP_URL || '';
const BASE_PATH = process.env.APP_BASE_PATH || '';

module.exports = {
  reactStrictMode: true,
  serverRuntimeConfig: {
    app_url: process.env.APP_URL || 'http://localhost:3000',
    app_env: process.env.APP_ENV || 'development',
    node_env: process.env.NODE_ENV || 'development',
    api_auth_secret: process.env.API_AUTH_SECRET || '',
    db_username: process.env.DB_USERNAME || '',
    db_password: process.env.DB_PASSWORD || '',
    db_hostname: process.env.DB_HOSTNAME || '',
    db_name: process.env.DB_NAME || '',
    database_url: process.env.DATABASE_URL || '',
    sso_configuration_endpoint: process.env.SSO_CONFIGURATION_ENDPOINT || '',
    sso_client_id: process.env.SSO_CLIENT_ID || '',
    keycloak_v2_dev_username: process.env.KEYCLOAK_V2_DEV_USERNAME || '',
    keycloak_v2_dev_password: process.env.KEYCLOAK_V2_DEV_PASSWORD || '',
    keycloak_v2_dev_url: process.env.KEYCLOAK_V2_DEV_URL || '',
    keycloak_v2_test_username: process.env.KEYCLOAK_V2_TEST_USERNAME || '',
    keycloak_v2_test_password: process.env.KEYCLOAK_V2_TEST_PASSWORD || '',
    keycloak_v2_test_url: process.env.KEYCLOAK_V2_TEST_URL || '',
    keycloak_v2_prod_username: process.env.KEYCLOAK_V2_PROD_USERNAME || '',
    keycloak_v2_prod_password: process.env.KEYCLOAK_V2_PROD_PASSWORD || '',
    keycloak_v2_prod_url: process.env.KEYCLOAK_V2_PROD_URL || '',
    ches_api_endpoint: process.env.CHES_API_ENDPOINT || '',
    ches_username: process.env.CHES_USERNAME || '',
    ches_password: process.env.CHES_PASSWORD || '',
    ches_token_endpoint: process.env.CHES_TOKEN_ENDPOINT || '',
    realm_registry_api: process.env.REALM_REGISTRY_API || '',
    grafana_api_token: process.env.GRAFANA_API_TOKEN || '',
    grafana_api_url: process.env.GRAFANA_API_URL || '',
    gold_ip_address: process.env.GOLD_IP_ADDRESS || '',
    include_digital_credential: process.env.INCLUDE_DIGITAL_CREDENTIAL || false,
    include_bc_services_card: process.env.INCLUDE_BC_SERVICES_CARD || false,
    ms_graph_api_authority: process.env.MS_GRAPH_API_AUTHORITY || '',
    ms_graph_api_client_id: process.env.MS_GRAPH_API_CLIENT_ID || '',
    ms_graph_api_client_secret: process.env.MS_GRAPH_API_CLIENT_SECRET || '',
    allow_bc_services_card_prod: process.env.ALLOW_BC_SERVICES_CARD_PROD || false,
    bcsc_registration_base_url_dev: process.env.BCSC_REGISTRATION_BASE_URL_DEV || '',
    bcsc_registration_base_url_test: process.env.BCSC_REGISTRATION_BASE_URL_TEST || '',
    bcsc_registration_base_url_prod: process.env.BCSC_REGISTRATION_BASE_URL_PROD || '',
    bcsc_initial_access_token_dev: process.env.BCSC_INITIAL_ACCESS_TOKEN_DEV || '',
    bcsc_initial_access_token_test: process.env.BCSC_INITIAL_ACCESS_TOKEN_TEST || '',
    bcsc_initial_access_token_prod: process.env.BCSC_INITIAL_ACCESS_TOKEN_PROD || '',
    redis_host: process.env.REDIS_HOST || '',
    gh_access_token: process.env.GH_ACCESS_TOKEN || '',
  },
  publicRuntimeConfig: {
    app_env: process.env.APP_ENV || 'develop',
    base_path: process.env.BASE_PATH,
    app_url: process.env.APP_URL,
    api_url: process.env.API_URL || '',
    sso_url: process.env.SSO_URL || 'http://localhost:8080',
    sso_client_id: process.env.SSO_CLIENT_ID || '',
    sso_redirect_uri: process.env.SSO_REDIRECT_URI || APP_URL || 'http://localhost:3000',
    sso_authorization_response_mode: process.env.SSO_AUTHORIZATION_RESPONSE_MODE || 'fragment', // 'query' | 'fragment'
    sso_authorization_response_type: process.env.SSO_AUTHORIZATION_RESPONSE_TYPE || 'code',
    sso_authorization_scope: process.env.SSO_AUTHORIZATION_SCOPE || 'openid',
    sso_token_grant_type: process.env.SSO_TOKEN_GRANT_TYPE || 'authorization_code',
    maintenance_mode: process.env.MAINTENANCE_MODE_ACTIVE || false,
    kc_idp_hint: process.env.KC_IDP_HINT || '',
    include_digital_credential: process.env.INCLUDE_DIGITAL_CREDENTIAL || false,
    include_bc_services_card: process.env.INCLUDE_BC_SERVICES_CARD || false,
    allow_bc_services_card_prod: process.env.ALLOW_BC_SERVICES_CARD_PROD || false,
    include_social: process.env.INCLUDE_SOCIAL || false,
  },
  env: {},
  assetPrefix: APP_URL,
  // basePath has to start with a /
  // basePath has to be either an empty string or a path prefix
  basePath: BASE_PATH,
};
