export const session = {
  at_hash: '',
  aud: '',
  auth_time: 1,
  azp: '',
  client_roles: ['sso-admin'],
  display_name: 'display_name',
  email: 'email@gov.bc.ca',
  email_verified: false,
  exp: 1,
  family_name: 'FN',
  given_name: 'GN',
  iat: 1,
  identity_provider: 'idir',
  idir_user_guid: '',
  idir_username: 'username',
  isAdmin: true,
  iss: '',
  jti: '',
  name: 'name',
  nonce: '',
  preferred_username: '',
  roles: ['sso-admin'],
  session_state: '',
  sid: '',
  sub: '',
  typ: 'ID',
};
