persistence:
  backup:
    size: 3Gi
  verification:
    size: 1Gi

env:
  ENVIRONMENT_FRIENDLY_NAME:
    value: 'SSO Request Dev Backup'
  ENVIRONMENT_NAME:
    value: b29129-dev
  WEBHOOK_URL:
    # value: '<<WEBHOOK URL FOR ROCKETCHAT>>'
    secure: true

  DAILY_BACKUPS:
    value: '7'
  WEEKLY_BACKUPS:
    value: '2'
  MONTHLY_BACKUPS:
    value: '1'
