image:
  tag: prod
  pullPolicy: Always

cronJobs:
  enabled: true
  image:
    tag: prod

api:
  enabled: true
  image:
    tag: prod
  extraEnvs:
    API_VERSION: v1
    API_ENV: production
    API_URL: https://api.loginproxy.gov.bc.ca
    MAINTENANCE_MODE_ACTIVE: 'false'
  route:
    host: sso-requests-api.apps.gold.devops.gov.bc.ca
    apiVanityHost: api.loginproxy.gov.bc.ca

env:
  NODE_ENV: production
  MAINTENANCE_MODE_ACTIVE: 'false'
  REALM_REGISTRY_API: https://realm-registry.apps.gold.devops.gov.bc.ca/api
  GOLD_IP_ADDRESS: '142.34.229.4'
  BCSC_REGISTRATION_BASE_URL_DEV: https://idtest.gov.bc.ca
  BCSC_REGISTRATION_BASE_URL_TEST: https://idtest.gov.bc.ca
  BCSC_REGISTRATION_BASE_URL_PROD: https://id.gov.bc.ca
  CHES_API_ENDPOINT: https://ches.api.gov.bc.ca/api/v1/email
  CHES_TOKEN_ENDPOINT: https://loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
  BCSC_SIGNING_ALGORITHM: PS256
  UPTIME_STATUS_DOMAIN_NAME: status.loginproxy.gov.bc.ca
  REDIS_RATE_LIMITER_LIMIT: 20

envVars: {}

route:
  host: sso-requests.apps.gold.devops.gov.bc.ca

patroni:
  replicaCount: 2

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: false

  persistentVolume:
    size: 1Gi
