name: Check pr labels

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  check-labels:
    name: Validate PR Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: minimum
          count: 1
          labels: 'bug, dependencies, documentation, duplicate, enhancement, feature, good first issue, help wanted, ignore-for-release, invalid, question, release:major, release:minor, ui-improvement, wontfix, miscellaneous'
