name: Run Keycloak App E2E tests

on:
  push:
    branches: ssoteam-1915
  workflow_dispatch:

env:
  CYPRESS_users: ${{ secrets.CYPRESS_USERS }}
  CYPRESS_guid: ${{ secrets.CYPRESS_GUID }}
  CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
  CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_host: 'https://bcgov.github.io/sso-requests-sandbox/'
  CYPRESS_smoketest: true
  CYPRESS_localtest: true
  CYPRESS_BASE_URL: 'https://bcgov.github.io/sso-requests-sandbox/'

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/external/*.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}
