name: Run Keycloak App E2E tests

on:
  # push:
  #   branches: ssoteam-1915
  workflow_dispatch:

env:
  CYPRESS_users: ${{ secrets.CYPRESS_USERS }}
  CYPRESS_guid: ${{ secrets.CYPRESS_GUID }}
  CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
  CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_host: 'https://bcgov.github.io/sso-requests-sandbox/'
  CYPRESS_smoketest: false
  CYPRESS_localtest: false
  CYPRESS_BASE_URL: 'https://bcgov.github.io/sso-requests-sandbox/'

jobs:
  pre-reqs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v4

      - name: Pre-requisites for test run
        uses: cypress-io/github-action@v6
        id: prereq
        continue-on-error: false
        with:
          summary-title: 'Pre-reqs'
          wait-on: https://bcgov.github.io/sso-requests-sandbox/
          wait-on-timeout: 120
          record: true
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/**/integration-990-deleteAllIntegrations.cy.ts
            cypress/e2e/**/team-900-*.cy.ts
          browser: electron
          # project: ./e2e
          ci-build-id: ${{ github.event.number }}

  idp-stopper:
    runs-on: ubuntu-latest
    needs: [pre-reqs, search-users, roles-tests]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/external/idpstopper-*.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}

  sso-tests:
    runs-on: ubuntu-latest
    needs: [pre-reqs, search-users, roles-tests, idp-stopper]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/external/sso-*.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}

  search-users:
    runs-on: ubuntu-latest
    needs: [pre-reqs]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/external/search-users.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}

  roles-tests:
    runs-on: ubuntu-latest
    needs: [pre-reqs]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/external/integration-roles.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}

  integration-tests:
    runs-on: ubuntu-latest
    needs: [pre-reqs]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: './docker-compose.yml'
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        id: smoke
        continue-on-error: false
        with:
          summary-title: 'E2E tests'
          record: true
          wait-on: 'https://bcgov.github.io/sso-requests-sandbox/'
          wait-on-timeout: 360
          install-command: yarn
          working-directory: app
          spec: |
            cypress/e2e/ci/integrations-crud.cy.ts
          browser: electron
          ci-build-id: ${{ github.event.number }}
